FROM archlinux:latest

RUN pacman -Syu --noconfirm remake

COPY pacman.conf /etc
COPY repo /var/cache/prolog
WORKDIR /var/cache/prolog
RUN repo-add prolog.db.tar.xz *.pkg.*

RUN pacman -Sy --noconfirm $PACKAGES

ARG USER
ARG GROUP

RUN groupadd -g $GROUP user
RUN useradd -ms /bin/sh -u $USER -g user user

USER user
WORKDIR /home/user/prolog

ENTRYPOINT ["remake"]
CMD ["-k", "-j4", "-O", "--profile", "all"]
