name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: archlinux-base-devel

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --progress=plain --compress --build-arg MYUSER=1000 --build-arg MYGROUP=1000 --tag my-image-name:$(date +%s) .
